version: '3.7'

services:
  postgres: 
    image: postgres
    environment:
      - POSTGRES_USER: "postgres"
      - POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres